name: "GitOps: Update Image Tag"
description: "Updates the Image Tag in a GitOps repository."
branding:
  icon: "package"
  color: "blue"

inputs:
  REPOSITORY_NAME:
    description: 'URL of the GitOps repository e.g. "adwert-it/infrastructure"'
    required: true
  BRANCH:
    description: 'Branch of the GitOps repository e.g. "main"'
    required: true
    default: "main"
  VALUES_FILE_PATH:
    description: 'Path to the values file in the GitOps repository e.g. "./deployments/helmCharts/projects/AdWert-IT/values.yaml"'
    required: true
  VALUE_PATH:
    description: 'Path of the value in the values file e.g. "spec.template.spec.containers[0].image"'
    required: true
  VALUES_FILE_PATH_2:
    description: 'Optional: Path to a second values file in the GitOps repository'
    required: false
  VALUE_PATH_2:
    description: 'Optional: Path of the value in the second values file'
    required: false
  VALUES_FILE_PATH_3:
    description: 'Optional: Path to a third values file in the GitOps repository'
    required: false
  VALUE_PATH_3:
    description: 'Optional: Path of the value in the third values file'
    required: false
  IMAGE:
    description: "Name of the Image e.g. '593793025909.dkr.ecr.us-east-1.amazonaws.com/triplezip-api:e0f9a8b'"
    required: true
  USERNAME:
    description: "Username for the GitOps repository. Defaults to the GITHUB_ACTOR."
    required: true
    default: ${{ github.actor }}
  ACCESS_TOKEN:
    description: "(Personal) Access Token for the GitOps repository. Defaults to the GITHUB_TOKEN."
    required: true
    default: ${{ github.token }}
  DEPLOYMENT_NAME:
    description: "Name of the deployment e.g. 'triplezip-api'"
    required: true
    default: "deployment"

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      run: |
        REPOSITORY_URL=https://${{ inputs.USERNAME }}:${{ inputs.ACCESS_TOKEN }}@github.com/${{ inputs.REPOSITORY_NAME }}.git
        git clone --depth 1 ${REPOSITORY_URL} --branch ${{ inputs.BRANCH }} --single-branch  ./repository
        cd ./repository
      shell: bash

    - name: Update Tag
      working-directory: ./repository
      run: |
        yq -i '.${{ inputs.VALUE_PATH }} = "${{ inputs.IMAGE }}"' ${{ inputs.VALUES_FILE_PATH }}
        if [ ! -z "${{ inputs.VALUES_FILE_PATH_2 }}" ] && [ ! -z "${{ inputs.VALUE_PATH_2 }}" ]; then
          yq -i '.${{ inputs.VALUE_PATH_2 }} = "${{ inputs.IMAGE }}"' ${{ inputs.VALUES_FILE_PATH_2 }}
        fi
        if [ ! -z "${{ inputs.VALUES_FILE_PATH_3 }}" ] && [ ! -z "${{ inputs.VALUE_PATH_3 }}" ]; then
          yq -i '.${{ inputs.VALUE_PATH_3 }} = "${{ inputs.IMAGE }}"' ${{ inputs.VALUES_FILE_PATH_3 }}
        fi
      shell: bash

    - name: Commit & Push
      working-directory: ./repository
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit --allow-empty -m "Update '${{ inputs.DEPLOYMENT_NAME }}' image to ${{ inputs.IMAGE }}"
        git pull --rebase
        git push
      shell: bash
